### STAGE 1: Build ###
FROM registry.access.redhat.com/ubi8/nodejs-16 AS build
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install --force
COPY . .
RUN npm run build

### STAGE 2: Run ###
FROM registry.access.redhat.com/ubi8/nginx-120
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/dist/kanban-ui /usr/share/nginx/html
EXPOSE 80