### STAGE 1: Build ###
FROM node:12.7-alpine AS build
USER root
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

### STAGE 2: Run ###
FROM registry.access.redhat.com/ubi8/nginx-120
COPY default.conf "${NGINX_DEFAULT_CONF_PATH}"
COPY --from=build /usr/src/app/dist/kanban-ui /opt/app-root/src
# Run script uses standard ways to run the application
CMD nginx -g "daemon off;"
EXPOSE 8080