FROM registry.access.redhat.com/ubi8/openjdk-11  AS build
USER root
RUN mkdir -p /workspace
WORKDIR /workspace
COPY pom.xml /workspace
COPY src /workspace/src
RUN mvn -f pom.xml clean package

FROM registry.access.redhat.com/ubi8/openjdk-11
USER root
COPY --from=build /workspace/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]