FROM registry.access.redhat.com/ubi9/python-311:1-66
WORKDIR /chat
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /chat/requirements.txt
COPY service.py .
EXPOSE 5000
ENTRYPOINT [ "python", "service.py" ]
